Revert "Adjust docker compose check command, only support compose V2."
This reverts commit dd682c7f55bd0bd3347a0f9353ebe94ea3594138.

diff --git a/sandbox b/sandbox
--- a/sandbox
+++ b/sandbox
@@ -43,9 +43,11 @@ export CONDUIT_SHA=""
 export CONDUIT_DISABLED=""
 
 ##################################################
-# Determine docker installed or fail #
+# Determine the correct docker command (or fail) #
 ##################################################
-if [ "$(docker compose --help &>/dev/null; echo "$?")" -eq 0 ]; then
+if [ -x "$(command -v docker-compose)" ]; then
+  DOCKER_COMPOSE="docker-compose"
+elif [ "$(docker compose help &>/dev/null; echo "$?")" -eq 16 ]; then
   DOCKER_COMPOSE="docker compose"
 else
   echo 'Error: docker compose is not installed.' >&2
