Better environment parameter initiailization.

diff --git a/sandbox b/sandbox
--- a/sandbox
+++ b/sandbox
@@ -116,38 +116,33 @@ sandbox () {
 
   # Start the algorand node
   up () {
-    # Initialize environment variables to configure and validate sandbox.
-    if [[ $# -gt 1 ]]; then
-      case $2 in
-        mainnet)
-          CHANNEL=stable
-          GENESIS_VERSION=mainnet-v1.0
-          SNAPSHOT_URL=$SNAPSHOT_MAINNET_URL
-          ;;
-        testnet)
-          CHANNEL=stable
-          GENESIS_VERSION=testnet-v1.0
-          SNAPSHOT_URL=$SNAPSHOT_TESTNET_URL
-          ;;
-        betanet)
-          CHANNEL=beta
-          GENESIS_VERSION=betanet-v1.0
-          CONFIG=beta.config.json
-          SNAPSHOT_URL=$SNAPSHOT_BETANET_URL
-          ;;
-        *)
-          err "Invalid network '$2', use one of ['mainnet', 'testnet', 'betanet']."
-          exit 1
-          ;;
-      esac
-    fi
-
     # Set default to testnet case a network wasn't provided
     NETWORK=${2:-testnet}
-    CHANNEL=${CHANNEL:-stable}
-    CONFIG=${CONFIG:-config.json}
-    SNAPSHOT_URL=${SNAPSHOT_URL:-}
-    GENESIS_VERSION=${GENESIS_VERSION:=testnet-v1.0}
+
+    case $NETWORK in
+      mainnet)
+        CHANNEL=stable
+        GENESIS_VERSION=mainnet-v1.0
+        CONFIG=config.json
+        SNAPSHOT_URL=$SNAPSHOT_MAINNET_URL
+        ;;
+      testnet)
+        CHANNEL=stable
+        GENESIS_VERSION=testnet-v1.0
+        CONFIG=config.json
+        SNAPSHOT_URL=$SNAPSHOT_TESTNET_URL
+        ;;
+      betanet)
+        CHANNEL=beta
+        GENESIS_VERSION=betanet-v1.0
+        CONFIG=beta.config.json
+        SNAPSHOT_URL=$SNAPSHOT_BETANET_URL
+        ;;
+      *)
+        err "Invalid network '$2', use one of ['mainnet', 'testnet', 'betanet']."
+        exit 1
+        ;;
+    esac
 
     # Validate/repair data directory
     if [[ -d data ]]; then
